### ISSUE TITLE
Headphone PCB BOM Issue

### ISSUE THREAD

**Issue by dmlr1996** [biologist79/ESPuino#100]
Hello there,

some weeks ago, you have provided the new and detailed BOM for the PCB's. Now we have the problem, that in the BOM for the Headphone PCB is a IC1 (ME6211C33m5g) written but we cant find the IC1 in the Schematic / on the ordered PCB. Do you have a solution fot that?

**Comment by biologist79** [comment]
Hi,

I forwarded this question to the guy that has been designing this PCB. He knows best, hehe.

**Comment by compactflash** [comment]
Hi @dmlr1996 
Maybe you have an old version of the BOM , the current ist [here](https://u.pcloud.link/publink/show?code=kZjJVKkZOYso9U99qILNOMm5ehliaFtxldWX) . I have made a 5V-version too , but the released one is for 3.3V . The ME6211 is not required .

**Comment by dmlr1996** [comment]
Hi @compactflash
thanks for your message. I have the BOM you provided to me in #93. I will check it again. Thanks.

**Comment by dmlr1996** [comment]
I have checked the BOM in the link you provided. There is a IC1 written for the headphone PCB. It's the same version like I have already. 
![grafik](https://user-images.githubusercontent.com/16854019/112141674-db642380-8bd5-11eb-9dcd-bbc09e85c917.png)

**Comment by dmlr1996** [comment]
Another thing we discovered today, neither the TDA1308 not the PT2308 are available at any of the nameable electronics distributors. Do you have any idea, how we can handle this?

**Comment by biologist79** [comment]
At least something I can answer :-)
https://de.aliexpress.com/item/33020207730.html

**Comment by dmlr1996** [comment]
Thanks @biologist79 the problem about it is the delivery time of 30-60 days .. xD

**Comment by biologist79** [comment]
In case you need some and you're from Germany: 20 of those are sitting next to me :-)

**Comment by dmlr1996** [comment]
Ja wenn das so ist, können wir auch deutsch schreiben :P
Das klingt gut. Mein kollege und ich bereiten gerade 5 Platinen vor, würdest du uns 5 Stück abgeben? Wenn ja, was sind wir dir schuldig?

**Comment by biologist79** [comment]
Mach's so: Melde mich in meinem ESPuino-Forum (https://forum.espuino.de/) am besten mal an - das geht auch mit den Github-Zugangsdaten. Und schreibe mir dort ne PM. Dann machen wir das dort :-)
