### ISSUE TITLE
Geht das auch auf einen M5 Core ?

### ISSUE THREAD

**Issue by ChR-iSz** [biologist79/ESPuino#109]
Hi,

ich nutze ein M5 Core (Geniales Teil!).
Meinst du es ist möglich, den Code darauf laufen zu lassen, und den internen Speakter + SDCard Slot + Display anzusteuern ? Quasi -> All in one Lösung ?!

Viele Grüße...

**Comment by biologist79** [comment]
Moin,

um ehrlich zu sein kann ich dir die Frage nicht beantworten.
Sie kam aber in meinem Forum bereits auf: https://forum.espuino.de/t/espuino-auf-dem-m5stack-gray-interner-dac/78
Also im Kern startet die Frage mit: Kriegst du die [Lib](https://github.com/schreibfaul1/ESP32-audioI2S), die ich zum Dekodieren verwende, darauf zum Laufen?

**Comment by biologist79** [comment]
Führt das Teil eigentlich auch GPIOs nach außen? Also SD scheint via SPI angebunden zu sein, das kann man 1:1 nutzen. Aber die Frage ist, wo man den RFID-Reader anschließt. Wobei man notfalls auf einen RC522 mit i2c zurückgreifen könnte, weil i2c wird ja verwendet. Kommt man an die Pins gut dran?

**Comment by schreibfaul1** [comment]
Hallo, ich vermute, dass es  funktionieren wird, testen kann ich das mangels HW nicht. In meinem Repository gibt es im Ordner examples Beispielcode für dem M5, der mir von den Usern zugeschickt wurde.

**Comment by biologist79** [comment]
Danke @schreibfaul1 für deinen Kommentar. Hatte ich nicht auf dem Schirm mit diesen Beispielen.
Wenn es das schon wirklich ist, dann wird es vermutlich tatsächlich funktionieren.
Die Frage ist im Endeffekt dann nur, wo man den RFID-Reader anschließt.

**Comment by schreibfaul1** [comment]
das könnte auch helfen:
https://macsbug.wordpress.com/2021/02/14/web_radio_of_m5stack_i2s_dac/

**Comment by ChR-iSz** [comment]
Danke Euch beiden. Ich werde mich da heute Abend mal ran machen. In Arduino bzw. Platformio bindet man einfach die M5Stack Bibliothek ein, und hat Zugriff auf RFID, SDCARD, Display, etc.

Ja, die PINS sind alle nach außen geführt. Ich habe noch das Batterie Modul-dran (auf dem Foto rotes Modul). Damit bleibt der ESP ca. 2 Tage autark vom Strom.

Komponenten gibt es on Mass: https://eckstein-shop.de/M5Stack-EN

Der RFID wird einfach eingesteckt und kostet ein paar Euro bei Eckstein.

Was mir daran gefällt, ist u.a.
A: Cover und Hörspielanzeige auf dem Display (?) (evtl. kann man dann auch die Lieder mal angenehm auswählen).
B: Sehr kompaktes Gerät,
C: Modular Plug'n Play Sensoren.,
D: Ein Lautsprecher ist bereits verbaut. Evtl reicht der für Hörspiele vollkommen aus (?). Ein externen Lautsprecher kann einfach an PIN 26 + Ground (DAC) angeschloßen werden.

Ich nutze Platformio (Arduino) in Visual Studio Code. Wenn ich soweit bin, werde ich Euch mal berichten, ob das alles so hingehauen hat.

Vielen dank nochmal für die schnelle Unterstützung ! 👍

![IMG_2436](https://user-images.githubusercontent.com/49807897/131458784-c2b0437a-dcb1-4960-a0b7-44b7049886ae.jpg)

![IMG_2437](https://user-images.githubusercontent.com/49807897/131458799-c2b7a5be-2c99-4855-9289-26bdeebe06e8.jpg)

**Comment by biologist79** [comment]
Klingt auf jeden Fall nach einem Projekt, das du in meinem Forum beschreiben könntest :-)

**Comment by biologist79** [comment]
Gibt's hier Neuigkeiten oder kann das geschlossen werden?

**Comment by ChR-iSz** [comment]
Ich denke das kann geschlossen werden. Ich habe es zwar geschafft, aber der interne Lautsprecher hat ein deutliches knacksen/rauschen beim abspielen.

VG

**Comment by drtrigon** [comment]
> Hallo, ich vermute, dass es funktionieren wird, testen kann ich das mangels HW nicht. In meinem Repository gibt es im Ordner examples Beispielcode für dem M5, der mir von den Usern zugeschickt wurde.

Wo ist das Beispiel? Ich würde ESPuino gerne auf einem M5Core2 mit RCA Module und M5GO Bottom 2 (RGB LEDs, kindgerechter Ladeanschluss) testen.

**Comment by biologist79** [comment]
Wir hatten das mal andiskutiert, aber ich wüsste nicht, dass das mal jmd. fertiggebracht hätte:
https://forum.espuino.de/t/espuino-auf-dem-m5stack-gray-interner-dac/78
