### ISSUE TITLE
What stereo DAC should I use?

### ISSUE THREAD

**Issue by majuss** [biologist79/ESPuino#110]
Are there any recommendations for stereo DACs? I need to drive two of these: https://www.ebay.de/itm/150510938590

Currently I'am experimenting with this DAC on my own breakout board: TI TLV320DAC3101. But I'am struggling heavily with all the BCLK/MCLK stuff. Do I need a dedicated Bit clock for this DAC or is it generated from the MCLK? I'am really confused :D

**Comment by biologist79** [comment]
PCM5102a for instance. Already used it along with a [headphone-PCB](https://github.com/biologist79/ESPuino/tree/master/PCBs/Headphone%20with%20PCM5102a%20and%20TDA1308).

**Comment by majuss** [comment]
Thank you I will look into that!
