### ISSUE TITLE
Deletion of a folder via FTP / WebUI

### ISSUE THREAD

**Issue by GeneralLuzi** [biologist79/ESPuino#118]
Hi all,

UseCase (SW-Revision: 20211113-2):

1. Create Folder via FTP - folder name: "üäö" (without "") (remark: I used utf-8 encoding during my ftp session - don't know if this was the issue)
2. Try to delete via FTP: deletion was not successful
3. Try to delete via WebUI: deletion was not successful

Thanks and regards,
GL

**Comment by biologist79** [comment]
Hi,
encoding needs to be set to CP437. 
It turned out this is the only way to have consistency between FTP, WebGUI and direct SD-transfer.

German manual: https://forum.espuino.de/t/dateiupload-auf-den-espuino/258

**Comment by biologist79** [comment]
Solved?

**Comment by GeneralLuzi** [comment]
yes... encoding CP437 is mandatory...

Thanks
