### ISSUE TITLE
MQTT: new brightness values not published

### ISSUE THREAD

**Issue by GeneralLuzi** [biologist79/ESPuino#119]
Hi,

while setting a new value for the loudness is working fine, brightness does not work properly IMHO.

Use Case for loudness:
1) ESPUINO_MQTT publishes on start e.g. 10.
2) PRIVATE_MQTT_CLIENT receives 10 
3) PRIVATE_MQTT_CLIENT publishes 11
4) ESPUINO_MQTT receives 11 and espuino sets loudness to 11
5) ESPUINO_MQTT  publishes 11
6) PRIVATE_MQTT_CLIENT receives 11 

Use Case for brightness:
1) ESPUINO_MQTT publishes on start e.g. 10.
2) PRIVATE_MQTT_CLIENT receives 10 
3) PRIVATE_MQTT_CLIENT publishes 11
4) ESPUINO_MQTT receives 11 and espuino sets brightness to 11
**-- NOT WORKING BELOW THIS LINE --**
5) ESPUINO_MQTT  publishes 11
6) PRIVATE_MQTT_CLIENT receives 11

Thanks and regards,
GL

**Comment by GeneralLuzi** [comment]
Same on:
- topicLockControlsCmnd
- Cmnd/ESPuino/SleepTimer

**Comment by biologist79** [comment]
Need to investigate.

**Comment by thebino** [comment]
I discovered the same issue today. Fix can be found here: https://github.com/biologist79/ESPuino/pull/124

**Comment by GeneralLuzi** [comment]
If you need a tester feel free to ask! :)Von: Benjamin Stürmer ***@***.***>Gesendet: Montag, 22. November 2021, 18:38An: biologist79/ESPuinoCc: GeneralLuzi; AuthorBetreff: Re: [biologist79/ESPuino] MQTT: new brightness values not published (Issue #119)
I discovered the same issue today. Fix can be found here: #124

**Comment by thebino** [comment]
@GeneralLuzi You can just checkout the branch and deploy it to your device. It will be reviewed this week anyway :D

**Comment by GeneralLuzi** [comment]
@thebino my test shows 2 out of 3. Well done!  👍 

Brightness and SleepTimer I can confirm to be fixed. Somehow LockControls is not publishing the change! Could you have a look please?

Thanks!

**Comment by thebino** [comment]
@GeneralLuzi can you pull the latest state and validate if it updates the state now? Haven't tested myself. Just added the fix and pushed it.

**Comment by biologist79** [comment]
Merged into master.
@GeneralLuzi Please review if it's working for you.

**Comment by GeneralLuzi** [comment]
Thanks @biologist79 

I retested the feature on the branch of @thebino this morning and it worked. Afterwards I wanted to test the RFID commands in combination with MQTT and discovered a major fail - my SD Card (filesystem?!) was destroyed... Not sure why and how... I am trying to recap... maybe a new issue - maybe just bad luck with the SD card not sure

After fixing the SD Card, I will test the merge and comment again...

**Comment by biologist79** [comment]
Can this one be closed?

**Comment by GeneralLuzi** [comment]
I will close this issue. Thanks for fixing. If there is anything left, I will re-open again.
