### ISSUE TITLE
USE_LAST_VOLUME_AFTER_REBOOT not working properly

### ISSUE THREAD

**Issue by GeneralLuzi** [biologist79/ESPuino#130]
Hi,

scenario 1:
- set volume to 11 without playing a song. In my case the starting point was 3. 
- go to deep sleep.
- wake up esp32 
- Issue: Volume is set to 9

scenario 2: 
- set volume to 11 without playing a song. In my case the starting point was 3. 
- go to deep sleep.
- reboot esp32 
- Issue: Volume is set to 9

Might be an issue.

Thanks and regards,
GL

**Comment by anoff** [comment]
Is your max volume set to 9 by any chance? 👀

I also had issues with this feature in the most recent SW and decided to disable it for now. But in my case the volume always started ~3

**Comment by biologist79** [comment]
Didn't forget you guys, sorry for the delay :-)
Will have a closer look ASAP. There's currently other stuff that needs my time.

**Comment by biologist79** [comment]
Cannot reproduce this issue with the current master (from today).

**Comment by biologist79** [comment]
Hmm, I cannot reproduce this issue with the current master.

**Comment by anoff** [comment]
I will retry with the latest version in the coming days. Was busy programming cards so I didn't see your response, sorry :D
