### ISSUE TITLE
Enable FTP via Web UI

### ISSUE THREAD

**Issue by anoff** [biologist79/ESPuino#134]
Thanks a lot for this project! When I first heard about Tonuino I set out to built my own version that supports proper file handling and also remote upload capability. Luckily I forgot about it for a while and then found ESPuino <3

Anyway, I was wondering if you'd be willing to support FTP Enabling via the Web UI.
There already is a FTP section, so it would only be one more button the UI on a relatively empty section.

Benefit: I don't need to walk to the device and push the button, I can do it all from my PC directly.
I would try to PR if you think this is an idea you like

**Comment by biologist79** [comment]
Enabling FTP via Webgui would be ok for me. Feel free to provide a PR :-)
