### ISSUE TITLE
HTMLmanagement_EN not containing coverimage

### ISSUE THREAD

**Issue by SZenglein** [biologist79/ESPuino#142]
Just noticed this difference. The coverimage seems to not be supported in the english version?

**Comment by tueddy** [comment]
Ich habe das zunächst nur für die deutsche HTML implementiert. 
Die englische Seite ist ja weitgehend redundant und soll mittelfristig durch eine einzige Seite mit dynamischer Lokalisierung ersetzt werden (I18N). Bislang hat sich dafür allerdings noch niemand gefunden..

**Comment by biologist79** [comment]
Fixed.
