### ISSUE TITLE
Battery Visualization while Charging

### ISSUE THREAD

**Issue by SZenglein** [biologist79/ESPuino#156]
I have been asked if it were possible to display charging progress while plugged in and turned off. Apparently it can be annoying to not see the charging state easily.

As this is not straightforward to implement, I want to gather a few ideas. Here is what I think is necessary:
* Hardware for "plugged-in" detection: charge controller or if USB has 5V
* A separate charging "off" state: muted, only LED active
* (Optional) An interrupt for instantly detecting being plugged in/out

Maybe it could be implemented without much effort by keeping the LEDs powered on in Deepsleep and waking up every few seconds to update the charging state.  
Alternatively, just idling with everything off and only showing percentage on the regular button combination would be a good solution.

**Comment by biologist79** [comment]
This is already possible using my [fepo](https://forum.espuino.de/t/esp32-develboard-d32-pro-lifepo4/1109) or [lipo](https://forum.espuino.de/t/esp32-develboard-e32-lipo/1135)-board. TP5000 provides a pin to indicate charge-state, so I routed it to a breakout pin "CHRG" of the develboard.
Please note: this pin is already used by the chrg-LED soldered on the develboard. Keep this in mind if you want to connect another LED. If this LED is removed, this chrg-pin could be connected to the port-expander. As chrg changes it's state when chrg is done, an interrupt is fired in this case. This would cause the ESP to wake up.
