### ISSUE TITLE
Sporadic Artifacts in WS2812 LEDs

### ISSUE THREAD

**Issue by Joe91** [biologist79/ESPuino#179]
There are sporadic artefacts / pixel errors. They are more likely at the higher the pixel-indexs. 
More noticable when using more LEDs.

Best guess so far:
Maybe the transmission gets interrupted / delayed by some Ethernet IRQs or Flash access?

Any idea on how to further narrow this down or on what to test further welcome:-).

Thanks for this great project!

**Comment by biologist79** [comment]
This is a known issue. Try to change LED-task's core from 0 to 1:
https://github.com/biologist79/ESPuino/blob/master/src/Led.cpp#L72

**Comment by Joe91** [comment]
Sorry, I haven't found any post to this topic in the forum that's why I created this issue.

Thank you very much! This really solves the visual issues.
What are the downsides of this (why is this not the default)?

**Comment by biologist79** [comment]
It's not default because sometimes "tiny stuff" can have massive side-effects @ESP32. As I currently don't have time to test it, it's not yet default.

**Comment by Joe91** [comment]
Thanks a lot for this answer and your support!
Do you prefer to use the forum for such stuff?

**Comment by biologist79** [comment]
Yes, I do :-)
