### ISSUE TITLE
Bug: Seek / jump backwards on mp3 not working

### ISSUE THREAD

**Issue by Joe91** [biologist79/ESPuino#180]
when using the command CMD_SEEK_BACKWARDS at least for the files I tested with it does not go backwards at all.

The positions get calculated correctly and the seek-command gets the right position, but it just doesn't appy. Forward works as intended.

Here some logs, including lots of debug stuff i wrote there:
`[ 219258 ]  Kommando: Pause
test debug
pos: 2446756, offset: -237480
pos: 2209276, offset: -237480
new pos: 2209276, filesize: 2806149, audiostart: 45
[ 221082 ]  30 Sekunden zurueck gesprungen
pos to set: 2209461
[ 221705 ]  info        : stream ready
test debug
pos: 2509828, offset: -237480
pos: 2272348, offset: -237480
new pos: 2272348, filesize: 2806149, audiostart: 45
[ 223392 ]  30 Sekunden zurueck gesprungen
pos to set: 2272451
[ 224029 ]  info        : stream ready`

You can see, that I pressed two times and the positon should have been smaller on the 2nd call.
Followed the signal to the line "audiofile.seek(m_resumeFilePos);" in Audio.cpp without any wrong behaviour...

Only tested with mp3 files so far.

**Comment by biologist79** [comment]
This is an issue of the underlying audiolib (and was fixed recently as for as I know).
