### ISSUE TITLE
RC522 does not process any rfid-codes

### ISSUE THREAD

**Issue by daywalker7911** [biologist79/ESPuino#203]
The log show that the rfid card is recognized, but the code is not transmittet to the rfid queue

**Comment by laszloh** [comment]
Hi,
We'll need more information to find the bug. 

Can you post the following information:
- which target are you using 
- a diff of your settings.h (or a list of features which differ from the [default](https://github.com/biologist79/ESPuino/blob/master/src/settings.h))?
- which revision of ESPuino are you using (if you are not using the master/HEAD)
- steps you did (f.e. if the bug happened with a card in NVS or with an unknown card, or with no cards at all)
- Any other information which can help to reproduce the bug

Also an extract of the Log would be good.

**Comment by biologist79** [comment]
Should be fixed now. Please test.
@laszloh You're totally right. But he already wrote me a private message.

**Comment by biologist79** [comment]
Issue still ongoing?
