### ISSUE TITLE
Critical Voltage in Web-Interface

### ISSUE THREAD

**Issue by SZenglein** [biologist79/ESPuino#207]
If SHUTDOWN_ON_BAT_CRITICAL is enabled, espuino shuts off if the voltage falls below the critical voltage setting. 
This setting is written to NVS and cannot easily be changed afterwards: because the NVS value is set, the settings.h value is ignored.

It should be easy to add the critical voltage option to battery settings, but I don't know if I can find the time. 
It could also be a good first contribution if someone is interested :).

**Comment by biologist79** [comment]
Would be fine :-)

**Comment by biologist79** [comment]
Any news on this one?

**Comment by tueddy** [comment]
fixed with https://github.com/biologist79/ESPuino/commit/014246ee723563aa09255c2fd5c820c0bdba6091
Thanks to @SZenglein !
