### ISSUE TITLE
Compile Error - PackageException ArduinoJson 6.21.3

### ISSUE THREAD

**Issue by ghbju10** [biologist79/ESPuino#277]
Moin,

following compile error occured

ESPuino Software-revision: 20231104-1
ESPuino Git-revision: 894c6d8-dirty
Arduino Version: 2.0.11 (ESP-IDF 4.4.5)
Hardware: ESP32-D0WD-V3, Revision 3, CPU: 240 MHZ

**PackageException: Package version 6.21.4+sha.3e1be98 doesn't satisfy requirements 6.21.3 based on PackageMetadata <type=library name=ArduinoJson version=6.21.4+sha.3e1be98 spec={'owner': None, 'id': None, 'name': 'ArduinoJson', 'requirements': '6.21.3', 'uri': 'git+https://github.com/bblanchon/ArduinoJson.git'}**

This works fine:

platformio.ini

lib_deps =
[...]
    ;https://github.com/bblanchon/ArduinoJson.git@6.21.3
    https://github.com/bblanchon/ArduinoJson.git#4b00783

**Comment by tueddy** [comment]
This issue has been already fixed in DEV branch. Referencing by version number does not always work.
Current ArduinoJson version 6.21.4:

https://github.com/bblanchon/ArduinoJson.git#3e1be98
