### ISSUE TITLE
API liefert nur RFID-ID als String statt vollständiger JSON-Antwort

### ISSUE THREAD

**Issue by paulwilke** [biologist79/ESPuino#286]
Hi,
ich bin auf ein Problem gestoßen, als ich eine spezifische RFID-ID über die API abgefragt habe (zum Beispiel über /rfid?id=060023033024). Statt einer detaillierten JSON-Antwort mit Informationen zur RFID, erhalte ich nur die ID als einfachen String. Ist dieses Verhalten beabsichtigt?

**Problematische Code-Stelle:**
Das Problem scheint in der handleGetRFIDRequest-Funktion in der Datei Web.cpp, speziell in Zeile 1794 zu liegen. Hier der betreffende Codeabschnitt:

https://github.com/biologist79/ESPuino/blob/a72421854b103d65829ad8c7bc62719e2078f7b9/src/Web.cpp#L1794

**Problem:**
Durch das Setzen des zweiten Arguments von tagIdToJsonStr auf true, gibt die Funktion lediglich die RFID-ID als String zurück. Dies entspricht nicht der erwarteten Funktionalität, zumindest aus meiner Sicht.

**Vorgeschlagener Fix:**
Das zweite Argument sollte auf false gesetzt werden. Dies würde sicherstellen, dass eine vollständige JSON-Antwort zurückgegeben wird, die detaillierte Informationen zur spezifischen RFID-ID enthält.

Sollte es für dieses Verhalten einen anderen Grund geben, würde ich alternativ vorschlagen, dass wir eine zusätzliche Route hinzufügen, um an die Details zu gelangen, z.B. über [GET] /rfid/id/060023.....

**Comment by tueddy** [comment]
Das war ein Bug und ist behoben mit [6a2adf5](https://github.com/biologist79/ESPuino/commit/6a2adf5fbf8dd7d9e0572649e977eb3c8e772d1d). Vielen Dank!
