### ISSUE TITLE
Software build (tag 2.2) is broken when NEOPIXEL_ENABLE is not set

### ISSUE THREAD

**Issue by RolinBert** [biologist79/ESPuino#289]
The software build is broken with the latest tag (2.2) when disabling the neopixel feature.

The build fails with an error message like this:
```
src/Led.cpp: In function 'void Led_SetNightmode(bool)':
src/Led.cpp:185:6: error: 'Led_NightMode' was not declared in this scope
  if (Led_NightMode == enabled) {
      ^~~~~~~~~~~~~
```

The reason for this is that in src\Led.cpp the methods "Led_SetNightmode", "Led_GetNightmode", "Led_ToggleNightmode" do not contain a pair of "#ifdef NEOPIXEL_ENABLE" and "#endif" as the other methods do.

**Comment by tueddy** [comment]
@RolinBert confirmed & fixed, thanls for your contribution!
