### ISSUE TITLE
Tracks with 1 channel have no sound

### ISSUE THREAD

**Issue by CheeseE** [biologist79/ESPuino#345]
Hello

Since the latest 2.3 release, audio files which have only 1 channel when played have no sound. Absolutely nothing can be heard from the speaker, but the track seems to play fine. No issue with 2 channel audio files. I have a 1 speaker setup.
I have tried both PLAY_MONO_SPEAKER enabled and disabled, but no change.
Attaching the log from a track with issues:
![image](https://github.com/user-attachments/assets/39838fa7-f0f1-451b-b96b-0738230842dd)
This was not an issue with the previous release, what should I do to fix this?

**Comment by biologist79** [comment]
Hi,

basically ESPuinos is not responsible for audio decoding. This having said we make use of https://github.com/schreibfaul1/ESP32-audioI2S/. As with 2.3 this version is in use: https://github.com/schreibfaul1/ESP32-audioI2S.git#d7a2007
You could try to replace this line (platformio.ini) with the old one https://github.com/schreibfaul1/ESP32-audioI2S.git#17f0e04.
Don't forget to run clean first - followed by "upload and monitor".

So at the end this is almost certainly a problem of the underlying lib. If that's the case, please report the problem there and don't foget to attach such an audio file.
