### ISSUE TITLE
MQTT Port

### ISSUE THREAD

**Issue by fladdie** [biologist79/ESPuino#92]
Hallo,

es wäre super wenn du bei MQTT noch den Port in der WebGui anpassbar machen könntest.

**Comment by biologist79** [comment]
Ja ich schau mal, was ich machen kann.
Ist grundsätzlich keine große Sache, aber ist gerade viel zu tun :-)

**Comment by fladdie** [comment]
Ausgezeichnet. Kein Stress. Wäre aber der Vollständigkeit wegen wirklich super. Am 19.02.2021 11:46 schrieb biologist79 <notifications@github.com>:

Ja ich schau mal, was ich machen kann.

Ist grundsätzlich keine große Sache, aber ist gerade viel zu tun :-)

**Comment by biologist79** [comment]
Erledigt.

**Comment by fladdie** [comment]
Ausgezeichnet. Wird morgen gleich geflasht!

1. März 2021 21:58, "biologist79" <notifications@github.com (mailto:notifications@github.com?to=%22biologist79%22%20<notifications@github.com>)> schrieb:
	Erledigt.
