### ISSUE TITLE
Missing Headphone PCB Partlist

### ISSUE THREAD

**Issue by dmlr1996** [biologist79/ESPuino#93]
Hello,

do you have a Partlist for the Headphone PCB?

Thanks.

**Comment by biologist79** [comment]
Hi,
forwarded your request to the person that's been creating this PCB. 
I'll add a BOM to the PCB-page here.

BR.

**Comment by compactflash** [comment]
Hi
[Link](https://u.pcloud.link/publink/show?code=kZjJVKkZOYso9U99qILNOMm5ehliaFtxldWX) to the Headphone PCB
