### ISSUE TITLE
main.cpp will not compile if PLAY_LAST_RFID_AFTER_REBOOT is defined

### ISSUE THREAD

**Issue by vrjpellenz** [biologist79/ESPuino#94]
... because there is an extra parenthesis:

line 459:
current version:
                loggerNl(serialDebug,((char *) FPSTR(unableToRestoreLastRfidFromNVS), LOGLEVEL_INFO);

fix:
                loggerNl(serialDebug,(char *) FPSTR(unableToRestoreLastRfidFromNVS), LOGLEVEL_INFO);

**Comment by biologist79** [comment]
Just fixed this.
Thanks for your report!
