### ISSUE TITLE
kicad project files are now missing in ESP32_Breakout_Carrier

### ISSUE THREAD

**Issue by phschoen** [biologist79/ESPuino#98]
hi,
with the Commit cc6df6d032251d630405e257fc5d93730c21d179
you deleted way to much. Now the gerber zip and **kicad project** files are not available any more. Please revert this change of at least the kicad files.
WBR Philipp

**Comment by biologist79** [comment]
Hi,

I deleted those as Tonuino is stated everywhere.
If you need it anyway maybe have a look at the fork by mariolokas. He's the one that provided it.

**Comment by biologist79** [comment]
But anyway: I agree it'd totally make sense to move all these single gerber-files into a single zip-file
